// styles/auth.styles.ts
import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  loginHeaderSafeArea: {
    backgroundColor: COLORS.accentRed,
  },
  loginHeader: {
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    alignItems: "flex-start",
  },
  loginHeaderBackButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  brandSection: {
    alignItems: "center",
    marginTop: height * 0.03,
    marginBottom: 8,
  },
  logoContainer: {
    width: 136,
    height: 136,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  loginLogoImage: {
    width: 128,
    height: 128,
  },
  appName: {
    fontSize: 42,
    fontWeight: "700",
    fontFamily: "JetBrainsMono-Medium",
    color: COLORS.accentRed,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  tagline: {
    fontSize: 16,
    color: COLORS.grey,
    letterSpacing: 1,
    textTransform: "lowercase",
  },
  illustrationContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  illustration: {
    width: width * 0.75,
    height: width * 0.75,
    maxHeight: 280,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  loginSection: {
    width: "100%",
    paddingHorizontal: 24,
    paddingBottom: 24,
    alignItems: "center",
  },
  form: {
    width: "100%",
    maxWidth: 340,
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.cartTextSecondary,
    marginBottom: 8,
  },
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.cartBorder,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    color: COLORS.cartTextPrimary,
    marginBottom: 16,
  },
  inputError: {
    borderColor: "#EF4444",
  },
  errorText: {
    fontSize: 12,
    color: "#EF4444",
    marginTop: -12,
    marginBottom: 12,
  },
  primaryButton: {
    backgroundColor: COLORS.accentRed,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 24,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 20,
    width: "100%",
    maxWidth: 340,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  dividerText: {
    fontSize: 13,
    color: COLORS.grey,
    paddingHorizontal: 16,
  },
  linkRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  linkText: {
    fontSize: 14,
    color: COLORS.grey,
  },
  link: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.accentRed,
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    marginBottom: 20,
    width: "100%",
    maxWidth: 340,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  googleIconContainer: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.cartTextPrimary,
  },
  termsText: {
    textAlign: "center",
    fontSize: 12,
    color: COLORS.grey,
    maxWidth: 280,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.cartTextPrimary,
    marginBottom: 20,
    textAlign: "center",
  },
  otpInput: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.cartBorder,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 20,
    color: COLORS.cartTextPrimary,
    textAlign: "center",
    letterSpacing: 8,
    marginBottom: 16,
  },
});
